use std::fmt::Write;

use p3_field::PrimeField32;
use spartan_whir::effective_digest_bytes_for_security_bits;

use crate::quartic_fixture::QuarticFixture;

pub fn generate_quartic_fixed_config_source(fixture: &QuarticFixture) -> String {
    generate_quartic_fixed_config_source_named(fixture, "QuarticWhirFixedConfig")
}

pub fn generate_quartic_fixed_config_source_named(
    fixture: &QuarticFixture,
    library_name: &str,
) -> String {
    let final_round = fixture.config.final_round_config();
    let effective_digest_bytes =
        effective_digest_bytes_for_security_bits(fixture.security.merkle_security_bits as usize);

    let mut out = String::new();
    writeln!(
        out,
        "// SPDX-License-Identifier: MIT\n\
         pragma solidity ^0.8.28;\n\n\
         import {{KeccakChallenger}} from \"../transcript/KeccakChallenger.sol\";\n\n\
         // This file is generated by spartan-whir-export. Do not edit by hand.\n\
         library {library_name} {{"
    )
    .unwrap();
    writeln!(
        out,
        "    using KeccakChallenger for KeccakChallenger.State;\n"
    )
    .unwrap();
    writeln!(
        out,
        "    struct RoundConfig {{\n\
         \tuint256 powBits;\n\
         \tuint256 foldingPowBits;\n\
         \tuint256 numQueries;\n\
         \tuint256 oodSamples;\n\
         \tuint256 numVariables;\n\
         \tuint256 foldingFactor;\n\
         \tuint256 domainSize;\n\
         \tuint256 foldedDomainGen;\n\
         \t}}\n"
    )
    .unwrap();

    emit_const(&mut out, "NUM_VARIABLES", fixture.config.num_variables);
    emit_const(
        &mut out,
        "COMMITMENT_OOD_SAMPLES",
        fixture.config.commitment_ood_samples,
    );
    emit_const(
        &mut out,
        "STARTING_FOLDING_POW_BITS",
        fixture.config.starting_folding_pow_bits,
    );
    let initial_sumcheck_rounds = fixture.config.round_parameters.first().map_or(
        fixture.config.num_variables - final_round.num_variables,
        |round| fixture.config.num_variables - round.num_variables,
    );
    emit_const(&mut out, "INITIAL_SUMCHECK_ROUNDS", initial_sumcheck_rounds);
    emit_const(
        &mut out,
        "FINAL_SUMCHECK_ROUNDS",
        fixture.config.final_sumcheck_rounds,
    );
    emit_const(
        &mut out,
        "FINAL_POLY_LENGTH",
        1usize << fixture.config.final_sumcheck_rounds,
    );
    emit_const(
        &mut out,
        "ROUND_COUNT",
        fixture.config.round_parameters.len(),
    );
    emit_const(&mut out, "FINAL_POW_BITS", final_round.pow_bits);
    emit_const(
        &mut out,
        "FINAL_FOLDING_POW_BITS",
        final_round.folding_pow_bits,
    );
    emit_const(&mut out, "FINAL_NUM_QUERIES", final_round.num_queries);
    emit_const(&mut out, "FINAL_NUM_VARIABLES", final_round.num_variables);
    emit_const(&mut out, "FINAL_FOLDING_FACTOR", final_round.folding_factor);
    emit_const(&mut out, "FINAL_DOMAIN_SIZE", final_round.domain_size);
    emit_const(
        &mut out,
        "FINAL_FOLDED_DOMAIN_GEN",
        final_round.folded_domain_gen.as_canonical_u32() as usize,
    );
    emit_const(
        &mut out,
        "EFFECTIVE_DIGEST_BYTES",
        effective_digest_bytes as usize,
    );
    emit_const(
        &mut out,
        "EXPECT_FINAL_QUERY_BATCH",
        usize::from(final_round.num_queries > 0),
    );
    emit_const(
        &mut out,
        "EXPECT_FINAL_SUMCHECK",
        usize::from(fixture.config.final_sumcheck_rounds > 0),
    );

    writeln!(
        out,
        "\n    function observePattern(KeccakChallenger.State memory challenger) internal pure {{"
    )
    .unwrap();
    // Emit a single bulk observeBytes with pre-encoded canonical LE bytes.
    // This is much cheaper than individual observeBase calls (~15k gas savings for 68 elements).
    let hex_blob: String = fixture
        .whir_fs_pattern
        .iter()
        .flat_map(|v| v.as_canonical_u32().to_le_bytes())
        .map(|b| format!("{b:02x}"))
        .collect();
    writeln!(
        out,
        "        challenger.observeBytes(\n            hex\"{hex_blob}\"\n        );"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();

    writeln!(
        out,
        "\n    function roundConfig(uint256 index) internal pure returns (RoundConfig memory cfg) {{"
    )
    .unwrap();
    for (index, round) in fixture.config.round_parameters.iter().enumerate() {
        writeln!(out, "        if (index == {index}) {{").unwrap();
        writeln!(
            out,
            "            return RoundConfig({{ powBits: {}, foldingPowBits: {}, numQueries: {}, oodSamples: {}, numVariables: {}, foldingFactor: {}, domainSize: {}, foldedDomainGen: {} }});",
            round.pow_bits,
            round.folding_pow_bits,
            round.num_queries,
            round.ood_samples,
            round.num_variables,
            round.folding_factor,
            round.domain_size,
            round.folded_domain_gen.as_canonical_u32()
        )
        .unwrap();
        writeln!(out, "        }}").unwrap();
    }
    writeln!(out, "        revert(\"ROUND_INDEX\");").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    out
}

fn emit_const(out: &mut String, name: &str, value: usize) {
    writeln!(out, "    uint256 internal constant {name} = {value};").unwrap();
}
